### ISSUE TITLE
get_clean_text function is inside datasets.preprocess.sentence

### ISSUE THREAD

**Issue by VinACE** [Renovamen/Text-Classification#3]
:~/Text-Classification$ python classify.py
Traceback (most recent call last):
  File "classify.py", line 6, in <module>
    from datasets.preprocess import get_clean_text
ImportError: cannot import name 'get_clean_text' from 'datasets.preprocess' (unknown location)

**Comment by VinACE** [comment]
changed the import in classify.py 
from datasets.preprocess.sentence import get_clean_text

**Comment by Renovamen** [comment]
Fixed in https://github.com/Renovamen/Text-Classification/commit/6fdf0bdcc3e0cd6f5da24cc25421e223a05345e4, thanks!
