### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by tuongtranngoc** [Renovamen/Text-Classification#5]
HI @Renovamen 
When run `classify.py`, it's oki, but move classify.py file to other anywhere: `ModuleNotFdeloundError: No module named 'models'`.
I know that model, epoch, optimizer, ... They have been saved in `.pth.tar`.
So, why?

Thank

**Comment by Renovamen** [comment]
Hi, as stated by PyTorch official, `torch.save` **does not save the model class itself**. Rather, it saves **a path to the file containing the class**. So the model class code and directory structure in test phase should be the same as those in training phase.

See here for more details: https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model

And I'm not sure if there's a way to save and load a PyTorch model without accessing to model class code...

**Comment by tuongtranngoc** [comment]
Hi @Renovamen,
thank you very much
